/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface RazorpayConfiguration {
  'secretKey' : string,
  'apiKey' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SignalingData {
  'offer' : [] | [string],
  'lastUpdated' : Time,
  'answer' : [] | [string],
  'iceCandidates' : Array<string>,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscription {
  'endDate' : [] | [Time],
  'type' : SubscriptionType,
  'user' : Principal,
  'isActive' : boolean,
  'startDate' : Time,
}
export type SubscriptionType = { 'basicPremium' : null } |
  { 'globalMatching' : null } |
  { 'videoCalling' : null } |
  { 'adFree' : null } |
  { 'premiumBundle' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserPreferences {
  'globalMatching' : boolean,
  'privacyLevel' : string,
  'voiceEnabled' : boolean,
  'videoEnabled' : boolean,
}
export interface UserProfile {
  'age' : bigint,
  'bio' : string,
  'kycVerified' : boolean,
  'name' : string,
  'onboardingComplete' : boolean,
  'preferences' : UserPreferences,
  'profilePicture' : [] | [ExternalBlob],
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YoutubeSessionState {
  'lastUpdated' : Time,
  'version' : bigint,
  'isPlaying' : boolean,
  'playbackPosition' : bigint,
  'videoId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addSubscription' : ActorMethod<[Subscription], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanupSignalingState' : ActorMethod<[Principal], undefined>,
  'cleanupYouTubeSessionState' : ActorMethod<[Principal], undefined>,
  'completeOnboarding' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOffer' : ActorMethod<[Principal, string], undefined>,
  'createRazorpayOrder' : ActorMethod<[bigint, string], string>,
  'exchangeCandidates' : ActorMethod<[Principal, string], undefined>,
  'findRandomPeer' : ActorMethod<[], [] | [Principal]>,
  'getActiveUserCount' : ActorMethod<[], bigint>,
  'getAds' : ActorMethod<[], Array<string>>,
  'getCallerSubscription' : ActorMethod<[], [] | [Subscription]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriends' : ActorMethod<[], Array<Principal>>,
  'getSignalingState' : ActorMethod<[Principal], [] | [SignalingData]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getYouTubeSessionState' : ActorMethod<
    [Principal],
    [] | [YoutubeSessionState]
  >,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isInMatchmakingPool' : ActorMethod<[], boolean>,
  'isRazorpayConfigured' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isVoiceReady' : ActorMethod<[], boolean>,
  'joinMatchmakingPool' : ActorMethod<[], undefined>,
  'leaveMatchmakingPool' : ActorMethod<[], undefined>,
  'matchWithPeer' : ActorMethod<[Principal], string>,
  'nextPeer' : ActorMethod<[], [] | [Principal]>,
  'removeInactiveUsers' : ActorMethod<[], undefined>,
  'respondToFriendRequest' : ActorMethod<[string, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendAnswer' : ActorMethod<[Principal, string], undefined>,
  'sendFriendRequest' : ActorMethod<[Principal], string>,
  'setRazorpayConfiguration' : ActorMethod<[RazorpayConfiguration], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setYouTubeSessionState' : ActorMethod<
    [Principal, YoutubeSessionState],
    undefined
  >,
  'terminateSession' : ActorMethod<[Principal], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateActivity' : ActorMethod<[], undefined>,
  'updateKycStatus' : ActorMethod<[Principal, boolean], undefined>,
  'verifyRazorpayPayment' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];