/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const SubscriptionType = IDL.Variant({
  'basicPremium' : IDL.Null,
  'globalMatching' : IDL.Null,
  'videoCalling' : IDL.Null,
  'adFree' : IDL.Null,
  'premiumBundle' : IDL.Null,
});
export const Subscription = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'type' : SubscriptionType,
  'user' : IDL.Principal,
  'isActive' : IDL.Bool,
  'startDate' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserPreferences = IDL.Record({
  'globalMatching' : IDL.Bool,
  'privacyLevel' : IDL.Text,
  'voiceEnabled' : IDL.Bool,
  'videoEnabled' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'kycVerified' : IDL.Bool,
  'name' : IDL.Text,
  'onboardingComplete' : IDL.Bool,
  'preferences' : UserPreferences,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
});
export const SignalingData = IDL.Record({
  'offer' : IDL.Opt(IDL.Text),
  'lastUpdated' : Time,
  'answer' : IDL.Opt(IDL.Text),
  'iceCandidates' : IDL.Vec(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const YoutubeSessionState = IDL.Record({
  'lastUpdated' : Time,
  'version' : IDL.Nat,
  'isPlaying' : IDL.Bool,
  'playbackPosition' : IDL.Nat,
  'videoId' : IDL.Text,
});
export const RazorpayConfiguration = IDL.Record({
  'secretKey' : IDL.Text,
  'apiKey' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addSubscription' : IDL.Func([Subscription], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cleanupSignalingState' : IDL.Func([IDL.Principal], [], []),
  'cleanupYouTubeSessionState' : IDL.Func([IDL.Principal], [], []),
  'completeOnboarding' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOffer' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'createRazorpayOrder' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'exchangeCandidates' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'findRandomPeer' : IDL.Func([], [IDL.Opt(IDL.Principal)], []),
  'getActiveUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getSignalingState' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SignalingData)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getYouTubeSessionState' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(YoutubeSessionState)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isInMatchmakingPool' : IDL.Func([], [IDL.Bool], ['query']),
  'isRazorpayConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isVoiceReady' : IDL.Func([], [IDL.Bool], ['query']),
  'joinMatchmakingPool' : IDL.Func([], [], []),
  'leaveMatchmakingPool' : IDL.Func([], [], []),
  'matchWithPeer' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'nextPeer' : IDL.Func([], [IDL.Opt(IDL.Principal)], []),
  'removeInactiveUsers' : IDL.Func([], [], []),
  'respondToFriendRequest' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendAnswer' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'setRazorpayConfiguration' : IDL.Func([RazorpayConfiguration], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setYouTubeSessionState' : IDL.Func(
      [IDL.Principal, YoutubeSessionState],
      [],
      [],
    ),
  'terminateSession' : IDL.Func([IDL.Principal], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateActivity' : IDL.Func([], [], []),
  'updateKycStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'verifyRazorpayPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const SubscriptionType = IDL.Variant({
    'basicPremium' : IDL.Null,
    'globalMatching' : IDL.Null,
    'videoCalling' : IDL.Null,
    'adFree' : IDL.Null,
    'premiumBundle' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'type' : SubscriptionType,
    'user' : IDL.Principal,
    'isActive' : IDL.Bool,
    'startDate' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserPreferences = IDL.Record({
    'globalMatching' : IDL.Bool,
    'privacyLevel' : IDL.Text,
    'voiceEnabled' : IDL.Bool,
    'videoEnabled' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'kycVerified' : IDL.Bool,
    'name' : IDL.Text,
    'onboardingComplete' : IDL.Bool,
    'preferences' : UserPreferences,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
  });
  const SignalingData = IDL.Record({
    'offer' : IDL.Opt(IDL.Text),
    'lastUpdated' : Time,
    'answer' : IDL.Opt(IDL.Text),
    'iceCandidates' : IDL.Vec(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const YoutubeSessionState = IDL.Record({
    'lastUpdated' : Time,
    'version' : IDL.Nat,
    'isPlaying' : IDL.Bool,
    'playbackPosition' : IDL.Nat,
    'videoId' : IDL.Text,
  });
  const RazorpayConfiguration = IDL.Record({
    'secretKey' : IDL.Text,
    'apiKey' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addSubscription' : IDL.Func([Subscription], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cleanupSignalingState' : IDL.Func([IDL.Principal], [], []),
    'cleanupYouTubeSessionState' : IDL.Func([IDL.Principal], [], []),
    'completeOnboarding' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOffer' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'createRazorpayOrder' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'exchangeCandidates' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'findRandomPeer' : IDL.Func([], [IDL.Opt(IDL.Principal)], []),
    'getActiveUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getSignalingState' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SignalingData)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getYouTubeSessionState' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(YoutubeSessionState)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isInMatchmakingPool' : IDL.Func([], [IDL.Bool], ['query']),
    'isRazorpayConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isVoiceReady' : IDL.Func([], [IDL.Bool], ['query']),
    'joinMatchmakingPool' : IDL.Func([], [], []),
    'leaveMatchmakingPool' : IDL.Func([], [], []),
    'matchWithPeer' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'nextPeer' : IDL.Func([], [IDL.Opt(IDL.Principal)], []),
    'removeInactiveUsers' : IDL.Func([], [], []),
    'respondToFriendRequest' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendAnswer' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'setRazorpayConfiguration' : IDL.Func([RazorpayConfiguration], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setYouTubeSessionState' : IDL.Func(
        [IDL.Principal, YoutubeSessionState],
        [],
        [],
      ),
    'terminateSession' : IDL.Func([IDL.Principal], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateActivity' : IDL.Func([], [], []),
    'updateKycStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'verifyRazorpayPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };